apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  api-app
  labels:
    name:  api-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  api-app
    spec:
      containers:
      - image:  apicrud:latest
        name:  api-app
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  api-app

---

apiVersion: v1
kind: Service
metadata:
  name: api-app-SVC
spec:
  selector:
    app: api-app
  ports:
  - port: 5000
    targetPort: 5000
