apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-app
  labels:
    name:  api-app
spec:
  selector:
    matchLabels:
      app: api-app
  replicas: 2  
  template:
    metadata:
      labels:
        app:  api-app
    spec:
      containers:
      - image:  jeanbsp/apicrud:1.0.1
        name:  api-app
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  api-app
      
      - image:  mysql:5.7
        name:  DB
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  33066
          name:  BD   
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: api-app
  name: api-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-app
  type: NodePort